# permissions for end users to view clusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterissuer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spire-broker-controller
    app.kubernetes.io/part-of: spire-broker-controller
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-viewer-role
rules:
- apiGroups:
  - spire.trustauth.net
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.trustauth.net
  resources:
  - clusterissuers/status
  verbs:
  - get
