---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - spire.byted.sh
  resources:
  - clusterissuers
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.byted.sh
  resources:
  - clusterissuers/status
  - issuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spire.byted.sh
  resources:
  - spires
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.byted.sh
  resources:
  - spires/finalizers
  verbs:
  - update
- apiGroups:
  - spire.byted.sh
  resources:
  - spires/status
  verbs:
  - get
  - patch
  - update
