# permissions for end users to view spires.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spire-issuer
    app.kubernetes.io/managed-by: kustomize
  name: spire-viewer-role
rules:
- apiGroups:
  - spire.byted.sh
  resources:
  - spires
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.byted.sh
  resources:
  - spires/status
  verbs:
  - get
