apiVersion: jubilant.trustauth.net/v1alpha1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: issuer
    app.kubernetes.io/instance: issuer-sample
    app.kubernetes.io/part-of: jubilant-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: jubilant-controller
  name: issuer-sample
spec:
  # TODO(user): Add fields here
  workMode: "downstream"
  spireAgentSocket: "unix:///tmp/spire-agent/public/api.sock"
  spireAddress: "127.0.0.1:8081"
