apiVersion: spire.trustauth.net/v1alpha1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: issuer
    app.kubernetes.io/instance: issuer-sample
    app.kubernetes.io/part-of: spire-broker-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spire-broker-controller
  name: issuer-sample
  namespace: default
spec:
  # TODO(user): Add fields here
  # workMode: "downstream"
  # secretName: "issuer-sample"
  trustDomain: "example.com"
  agentSocket: "/tmp/spire-agent/public/api.sock"
  spireAddress: "127.0.0.1:18081"
