apiVersion: spire.byted.sh/v1alpha1
kind: SpireIssuer
metadata:
  name: sample-2
  namespace: default
  labels:
    app.kubernetes.io/name: issuer
    app.kubernetes.io/instance: issuer-sample
    app.kubernetes.io/part-of: spire-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spire-issuer
spec:
  # TODO(user): Add fields here
  trustDomain: "example.com"
  agentSocket: "/tmp/spire-agent/public/api.sock"
  spireAddress: "127.0.0.1:8081"
