apiVersion: spire.trustauth.net/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: clusterissuer
    app.kubernetes.io/instance: clusterissuer-sample
    app.kubernetes.io/part-of: spire-broker-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spire-broker-controller
  name: clusterissuer-sample
spec:
  # TODO(user): Add fields here
